エラー処理を追加

diff --git a/probo b/probo
--- a/probo
+++ b/probo
@@ -48,8 +48,7 @@ function generate-probo-schedule {
     local UNIT="$PROBO_BD_EXEC_PER_DAY"
     local REST=$(find . -name '*.testcase.md' | wc -l)
 
-    if [ -z "$CURDATE" ] || [ -z "$ENDDATE" ]; then
-        echo "ERROR: Invalid date specifier : PROBO_BD_STARTDAY or PROBO_BD_ENDDAY."
+    if [ -z "$CURDATE" ] || [ -z "$ENDDATE" ] || [ -z "$UNIT" ]; then
         return 1
     fi
 
@@ -66,6 +65,9 @@ function generate-probo-schedule {
             break
         fi
         CURDATE=$(date -d "$CURDATE + 1 day" +"%Y-%m-%d")
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
     done
 }
 
@@ -96,7 +98,7 @@ function generate-burndown-data-file-raw {
     local TODAY=$(date '+%Y-%m-%d')
     local REST1=$(find . -name '*.testcase.md' | wc -l)    # 基準線用残数
     local REST2=$REST1                                     # 実績用残数
-    echo "日付	期待値	消化数	Fail数	基準線	実績" > "${DAT_FILE}"
+    echo "日付	期待値	PASS数	FAIL数	基準線	実績" > "${DAT_FILE}"
     for LINE in ${PROBO_BD_SCHEDULE}
     do
         local DATE=$(echo      "$LINE" | cut -d , -f 1)
@@ -727,6 +729,10 @@ fi
 
 if [ -z "${PROBO_BD_SCHEDULE}" ]; then
     PROBO_BD_SCHEDULE=$(generate-probo-schedule)
+    if [ $? -ne 0 ]; then
+        echo "ERROR : Schedule generation failed."
+        exit 1
+    fi
 fi
 
 
